name: Marcosncosta
favicon: null
layout_spectrum: 0.51005
typography_spectrum: 0.78978
title: Athlete Bio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-27842471-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7e6851'
    - '#a29278'
    - '#130b08'
    - '#d9cc40'
    - '#ced5df'
  brandStrength: 0.375
  lightness: 0.75
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
