name: Marcosncosta
favicon: null
layout_spectrum: 0.59821
typography_spectrum: 0.78978
title: Athlete Bio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-27842471-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#6c717a'
    - '#d5d6db'
    - '#a88a03'
  brandStrength: 0.5625
  lightness: 0.625
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
