layout_spectrum: 0.011876023840159178
typography_spectrum: 0.04067429970018566
color:
  saturation: 0.3709691814146936
  brandStrength: 0.1873185085132718
  lightness: 0.3348039574921131
  brandColors:
    - '#2A2623'
    - '#969593'
    - '#545C37'
    - '#D3DDF6'
    - '#BAB6B3'
  rhythmicContrast: 0.4363797821570188
opengraph:
  image: null
  type: null
  appId: null
analytics:
  twitter: null
  google: UA-27842471-2
  facebook: null
name: Marcosncosta
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: Intro
    id: 25b67133-9d76-426d-a5d4-d9c3e7818075
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Athlete Bio
purpose: []
