typography_spectrum: 0.78978
color:
  saturation: 0.6760651
  brandStrength: 0.5
  lightness: 0.6710526
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#6c717a'
    - '#d5d6db'
    - '#a88a03'
  rhythmicContrast: 0.6127819
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.3477444
analytics:
  twitter: null
  google: UA-27842471-2
  facebook: null
name: Marcosncosta
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: Intro
    id: 25b67133-9d76-426d-a5d4-d9c3e7818075
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Athlete Bio
purpose: []
