name: Marcosncosta
favicon: null
layout_spectrum: 0.7092873335350305
typography_spectrum: 0.7036801592912525
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.438547152094543
  lightness: 0.5937303584069014
  saturation: 0.1583815598860383
  rhythmicContrast: 0.07831592531874776
purpose: []
