name: Marcosncosta
favicon: null
layout_spectrum: 1
typography_spectrum: 0.7036801592912525
title: Athlete Bio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-27842471-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#fdd831'
    - '#aacae8'
    - '#414045'
    - '#fa0d1b'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
